export const ITEM_DEFINITIONS = {
    0: { name: "Vacio", category: "Otros" },
    1: { name: "Nudillera", category: "Armas" },
    2: { name: "Palo de golf", category: "Armas" },
    3: { name: "Porra", category: "Armas" },
    4: { name: "Navaja", category: "Armas" },
    5: { name: "Bate", category: "Armas" },
    6: { name: "Pala", category: "Armas" },
    7: { name: "Palo de billar", category: "Armas" },
    8: { name: "Katana", category: "Armas" },
    9: { name: "Motosierra", category: "Armas" },
    10: { name: "Consolador rosa", category: "Otros" },
    11: { name: "Consolador pequeño", category: "Otros" },
    12: { name: "Consolador largo", category: "Otros" },
    13: { name: "Consolador plateado", category: "Otros" },
    14: { name: "Flores", category: "Otros" },
    15: { name: "Baston", category: "Armas" },
    16: { name: "Granada", category: "Explosivos" },
    17: { name: "Granada de gas", category: "Explosivos" },
    18: { name: "Coctel molotov", category: "Explosivos" },
    19: { name: "9mm", category: "Armas" },
    20: { name: "9mm con silenciador", category: "Armas" },
    21: { name: "Desert eagle", category: "Armas" },
    22: { name: "Escopeta", category: "Armas" },
    23: { name: "Recortada", category: "Armas" },
    24: { name: "Escopeta de combate", category: "Armas" },
    25: { name: "Uzi", category: "Armas" },
    26: { name: "MP5", category: "Armas" },
    27: { name: "Ak47", category: "Armas" },
    28: { name: "M4", category: "Armas" },
    29: { name: "Tec9", category: "Armas" },
    30: { name: "Rifle de caza", category: "Armas" },
    31: { name: "Rifle de francotirador", category: "Armas" },
    32: { name: "Lanzamisiles", category: "Armas" },
    33: { name: "RPG-7", category: "Armas" },
    34: { name: "Lanzallamas", category: "Armas" },
    35: { name: "Minigun", category: "Armas" },
    36: { name: "Spray", category: "Herramientas" },
    37: { name: "Extintor", category: "Herramientas" },
    38: { name: "Camara fotografica", category: "Fotografia" },
    39: { name: "Paracaidas", category: "Paracaidas" },
    40: { name: "Taser", category: "Armas" },
    41: { name: "Encendedor", category: "Herramientas" },
    42: { name: "Paquete de cigarros", category: "Otros" },
    43: { name: "Marihuana", category: "Drogas" },
    44: { name: "Crack", category: "Drogas" },
    45: { name: "Metanfetamina", category: "Drogas" },
    46: { name: "Cocaina", category: "Drogas" },
    47: { name: "Gallo de marihuana", category: "Drogas" },
    48: { name: "Blunt de marihuana", category: "Drogas" },
    49: { name: "Cigarro", category: "Otros" },
    50: { name: "Telefono", category: "Herramientas" },
    51: { name: "Boombox", category: "Herramientas" },
    52: { name: "Dinamita", category: "Explosivos" },
    53: { name: "Botiquin", category: "Medicos" },
    54: { name: "Beanbag", category: "Armas" },
    55: { name: "Caja personal", category: "Otros" },
    56: { name: "Cargador 9mm", category: "Municion" },
    57: { name: "Cargador desert eagle", category: "Municion" },
    58: { name: "Cargador uzi", category: "Municion" },
    59: { name: "Cargador mp5", category: "Municion" },
    60: { name: "Cargador tec9", category: "Municion" },
    61: { name: "Cargador ak47", category: "Municion" },
    62: { name: "Cargador m4a1", category: "Municion" },
    63: { name: "Cartuchos de rifle", category: "Municion" },
    64: { name: "Cartuchos de escopeta", category: "Municion" },
    65: { name: "Cerveza", category: "Bebidas" },
    66: { name: "Chaleco", category: "Ropa" },
    67: { name: "Sixpack de cerveza", category: "Bebidas" },
    68: { name: "Ropa", category: "Ropa" },
    69: { name: "Desactivado(4)", category: "Otros" },
    70: { name: "Desactivado(5)", category: "Otros" },
    71: { name: "Desactivado(6)", category: "Otros" },
    72: { name: "Naloxona", category: "Medicos" },
    73: { name: "Desactivado(8)", category: "Otros" },
    74: { name: "Desactivado(9)", category: "Otros" },
    75: { name: "Planta de cocaina", category: "Drogas" },
    76: { name: "Desactivado(10)", category: "Otros" },
    77: { name: "Desactivado(11)", category: "Otros" },
    78: { name: "Fertilizante", category: "Herramientas" },
    79: { name: "Cigarro electrico", category: "Otros" },
    80: { name: "Wax", category: "Drogas" },
    81: { name: "Orange Kush", category: "Drogas" },
    82: { name: "Gorilla Glue", category: "Drogas" },
    83: { name: "Semilla de marihuana", category: "Drogas" },
    84: { name: "Diazepam", category: "Medicos" },
    85: { name: "Semilla de coca", category: "Drogas" },
    86: { name: "Whisky", category: "Bebidas" },
    87: { name: "Champagne", category: "Bebidas" },
    88: { name: "Vodka", category: "Bebidas" },
    89: { name: "Tequila", category: "Bebidas" },
    90: { name: "Ron", category: "Bebidas" },
    91: { name: "Coñac", category: "Bebidas" },
    92: { name: "Ginebra", category: "Bebidas" },
    93: { name: "Mascara", category: "Ropa" },
    94: { name: "Chaleco de airsoft", category: "Ropa" },
    95: { name: "Replica de Rifle", category: "Armas" },
    96: { name: "Replica de M4", category: "Armas" },
    97: { name: "Replica de Desert eagle", category: "Armas" },
    98: { name: "Replica de Escopeta", category: "Armas" },
    99: { name: "Replica de cargador", category: "Municion" },
    100: { name: "Lanzador .40mm", category: "Armas" },
    101: { name: "Caja proyectiles .40mm", category: "Municion" },
    102: { name: "Bolsa de Anfetamina", category: "Drogas" },
    103: { name: "Bolsa de Metadona", category: "Drogas" },
    104: { name: "Bolsa de Diazepam", category: "Drogas" },
    105: { name: "Bolsa de Oxicodona", category: "Drogas" },
    106: { name: "Bolsa de Naloxona", category: "Medicos" },
    107: { name: "Bolsa de MDMA", category: "Drogas" },
    108: { name: "Bolsa de LSD", category: "Drogas" },
    109: { name: "Bolsa de Heroina", category: "Drogas" },
    110: { name: "Bolsa de Ketamina", category: "Drogas" },
    111: { name: "Caja de 9mm", category: "Armas" },
    112: { name: "Caja de 9mm con silenciador", category: "Armas" },
    113: { name: "Caja de DK", category: "Armas" },
    114: { name: "Caja de Escopeta", category: "Armas" },
    115: { name: "Caja de Recortada", category: "Armas" },
    116: { name: "Caja de Escopeta de combate", category: "Armas" },
    117: { name: "Caja de Uzi", category: "Armas" },
    118: { name: "Caja de MP5", category: "Armas" },
    119: { name: "Caja de Ak47", category: "Armas" },
    120: { name: "Caja de M4", category: "Armas" },
    121: { name: "Caja de Tec9", category: "Armas" },
    122: { name: "Caja de cargadores de 9mm", category: "Municion" },
    123: { name: "Caja de cargadores de Desert eagle", category: "Municion" },
    124: { name: "Caja de cargadores de Uzi", category: "Municion" },
    125: { name: "Caja de cargadores de MP5", category: "Municion" },
    126: { name: "Caja de cargadores de Ak47", category: "Municion" },
    127: { name: "Caja de cargadores de M4", category: "Municion" },
    128: { name: "Caja de cargadores de Tec9", category: "Municion" },
    129: { name: "Hotdog Pequeño", category: "Alimentos" },
    130: { name: "Hotdog Mediano", category: "Alimentos" },
    131: { name: "Hotdog Grande", category: "Alimentos" },
    132: { name: "Lata de Sprunk", category: "Bebidas" },
    133: { name: "Botella de agua", category: "Bebidas" },
    134: { name: "Bolsa de doritos", category: "Alimentos" },
    135: { name: "Bolsa de patatas", category: "Alimentos" },
    136: { name: "Bolsa de nachos", category: "Alimentos" },
    137: { name: "Hamburguesa", category: "Alimentos" },
    138: { name: "Burrito", category: "Alimentos" },
    139: { name: "Pizza", category: "Alimentos" },
    140: { name: "Taco", category: "Alimentos" },
    141: { name: "Cafe", category: "Bebidas" },
    142: { name: "Carne humana", category: "Alimentos" },
    // Faction Weapons & Items
    143: { name: "USP9", category: "Armas" },
    144: { name: "USP9SD", category: "Armas" },
    145: { name: "USP45", category: "Armas" },
    146: { name: "Remington M870", category: "Armas" },
    147: { name: "Franchi SPS 230", category: "Armas" },
    148: { name: "H&K MP5K", category: "Armas" },
    149: { name: "AK-74M", category: "Armas" },
    150: { name: "HK-416", category: "Armas" },
    151: { name: "M14", category: "Armas" },
    152: { name: "Barrett M82", category: "Armas" },
    153: { name: "M4A1", category: "Armas" },
    154: { name: "M24", category: "Armas" },
    155: { name: "HK-417", category: "Armas" },
    156: { name: "G36", category: "Armas" },
    157: { name: "MK18", category: "Armas" },
    158: { name: "P320", category: "Armas" },
    159: { name: "Five-seveN", category: "Armas" },
    160: { name: "Glock 17", category: "Armas" },
    161: { name: "Remington 1100", category: "Armas" },
    162: { name: "M110", category: "Armas" },
    163: { name: "MP7A1", category: "Armas" },
    164: { name: "Clip 919mm Parabellum", category: "Municion" },
    165: { name: "Clip .45 ACP", category: "Municion" },
    166: { name: "Clip 5.7x28mm", category: "Municion" },
    167: { name: "Clip 10.25mm", category: "Municion" },
    168: { name: "Clip 4,6x30mm", category: "Municion" },
    169: { name: "Clip 7,62x51mm NATO", category: "Municion" },
    170: { name: "Clip 5,56.45mm NATO", category: "Municion" },
    171: { name: "Magazine .50 BMG", category: "Municion" },
    172: { name: "Magazine 7,62x51 NATO", category: "Municion" },
    173: { name: ".12 Gauge", category: "Municion" },
    174: { name: "Vendas", category: "Medicos" },
    175: { name: "Sangre", category: "Medicos" },
    176: { name: "Mobile Data Computer", category: "Herramientas" },
    177: { name: "Microfono", category: "Herramientas" },
    178: { name: "Ropa", category: "Ropa" },
    179: { name: "Escudo Balistico", category: "Escudos" },
    180: { name: "Tarjeta Debito", category: "Dinero" },
    181: { name: "Radio", category: "Herramientas" },
    182: { name: "Auriculares", category: "Herramientas" },
    183: { name: "Bolso", category: "Mochilas" },
    184: { name: "Bolso Lleno", category: "Mochilas" },
    185: { name: "Kit de Reparacion", category: "Herramientas" },
    186: { name: "Kit de Herramientas", category: "Herramientas" },
    187: { name: "Ropa", category: "Ropa" },
    188: { name: "Disp. Matricula", category: "Herramientas" },
    189: { name: "Lata de Gasolina", category: "Herramientas" },
    190: { name: "Caja de Marihuana", category: "Drogas" },
    191: { name: "Caja de Crack", category: "Drogas" },
    192: { name: "Caja de Metanfetamina", category: "Drogas" },
    193: { name: "Caja de Cocaina", category: "Drogas" },
    194: { name: "Donas", category: "Alimentos" },
    195: { name: "Pan", category: "Alimentos" },
    196: { name: "Tomate", category: "Alimentos" },
    197: { name: "Carne", category: "Alimentos" },
    198: { name: "Algas", category: "Alimentos" },
    199: { name: "Pescado", category: "Alimentos" },
    200: { name: "Leche", category: "Bebidas" },
    201: { name: "Masa", category: "Alimentos" },
    202: { name: "Queso", category: "Alimentos" },
    203: { name: "Sushi Casero", category: "Alimentos" },
    204: { name: "Hamburguesa Casera", category: "Alimentos" },
    205: { name: "Leche Hervida", category: "Bebidas" },
    206: { name: "Carne Asada", category: "Alimentos" },
    207: { name: "Asador", category: "Herramientas" },
    208: { name: "Carbon", category: "Herramientas" },
    209: { name: "Mochila Comun", category: "Mochilas" },
    210: { name: "Fajo de Dinero", category: "Dinero" },
    211: { name: "Mochila Especial", category: "Mochilas" },
    212: { name: "Mochila Especial", category: "Mochilas" },
    213: { name: "Mochila Especial", category: "Mochilas" },
    214: { name: "Mochila Especial", category: "Mochilas" },
    215: { name: "Mochila Especial", category: "Mochilas" },
    216: { name: "Mochila Especial", category: "Mochilas" },
    217: { name: "Mochila", category: "Mochilas" },
    218: { name: "Mochila Especial", category: "Mochilas" },
    219: { name: "Mochila Especial", category: "Mochilas" },
    220: { name: "Mochila Especial", category: "Mochilas" },
    221: { name: "Adorno Navideño", category: "Decoracion" },
    222: { name: "Estrella Navideña", category: "Decoracion" },
    223: { name: "Parche Transdermico", category: "Medicos" },
    224: { name: "Block de Notas", category: "Utiles" },
    225: { name: "Hojas para Block", category: "Utiles" },
    226: { name: "Destornillador", category: "Utiles" }
};

export const getItemInfo = (id) => {
    return ITEM_DEFINITIONS[id] || { name: "Desconocido", category: "Otros" };
};
